### ISSUE TITLE
New Update Broke API for Updaters

### ISSUE THREAD

**Issue by astronautlevel2** [astronautlevel2/Luma3DS#7]
See conversation in #6
Tagging @KunoichiZ as they're relevant

ToDo:
- [x] Auto update latest.zip
- [ ] Auto update release.zip
- [x] Add latest commit number back

**Comment by fanfan54old** [comment]
Hello,
I have an old 3DS with Luma3DS (boot9strap) on SD and on NAND
Yesterday I updated to "normal version" with the Updater, but I was already on 7.1 so I don't know what it did.
I tried Luma Updater today, there is only one option available, this Updater is really buggy... maybe we should add an issue to Hamcha's repository? Many people are already complaining there
it's now saying:

Luma Updater v1.4.2
**Configuration not found, using default values**
Payload type: **arm9loaderhax**
Payload path: **/arm9loaderhax.bin**
Backup payload: yes

Current installed version: **7.1-c73fec46 (dev)**
Latest version (Github): **7.1**
Latest hourly build:

A new hourly build of Luma3DS is available.
-> Install normal version

Release notes for v7.1

-----
Oh, and when I choose to update to normal version, it says **Update failed** because of:
Extracting payload [ERR]
FATAL: could not find arm9loaderhax.binFATAL
Could not get A9LH payload...


But, I have a recent Boot9Strap install, and I never installed A9LH 🤦‍♂️ 
Good luck

**Comment by fanfan54old** [comment]
(...my bad, I'll just download the @KunoichiZ fork, version 2.0 and I'll only'post again here if it did something different than the screenshot on #6 )

**Comment by KunoichiZ** [comment]
@fanfan54 If you're talking about my screenshot, you won't see that on v2.0. I'm working on the next update and we're trying to figure out the hourly issue.

**Comment by astronautlevel2** [comment]
I've added back in the latest.zip and the lastCommit in https://github.com/astronautlevel2/Luma3DS-Nightlies/commit/eb6a01322e143536138e2a13cdc0e33407f0867b, and will add the release.zip later (but as Luma Update downloads the latest release from AW's github it shouldn't be a huge issue)

**Comment by KunoichiZ** [comment]
I'm trying to figure out which URL to use. Going to the URL provided in BuildScript.sh (Luma3DS-Site) gives the Github no pages site error. 

And would I use the raw URL ([like this](https://raw.githubusercontent.com/astronautlevel2/Luma3DS-Site/lastCommit)) or an api.github.com URL to get the last commit? I'm guess I'm just confused on what URL to use to fetch everything.

**Comment by astronautlevel2** [comment]
You want to use this:
http://astronautlevel2.github.io/Luma3DS/lastCommit

**Comment by KunoichiZ** [comment]
Thanks! And would the build URL still be [this](http://astronautlevel2.github.io/Luma3DS/builds/Luma3DS-) with the commit attached to it?

**Comment by astronautlevel2** [comment]
The most recent commit is still http://astronautlevel2.github.io/Luma3DS/latest.zip

**Comment by KunoichiZ** [comment]
And that will be updated automatically now? I'm sorry if I'm asking too many questions about this. I just want to make sure I have everything correct.

**Comment by astronautlevel2** [comment]
Hey, it's not problem!

Yeah, that'll be updated automatically now. If you want to contact me more about this it may be easier to contact me over discord (astronautlevel#3876) instead of continuing the discussion on github issues :P

**Comment by KunoichiZ** [comment]
I just sent a friend request.

**Comment by laincat** [comment]
https://github.com/AuroraWright/Luma3DS/tree/b9s-next

**Comment by astronautlevel2** [comment]
@laincat opening new issue for this

**Comment by MelonGx** [comment]
Is the luma auto builder crashed by devkitARM, ctrulib, firmtool not updated?
One of us can build it in Linux with all the 3 of them updated to the latest, but no good news for Windows.

**Comment by astronautlevel2** [comment]
@MelonGx the required version for firmtool changed from 1.0 to 1.1, and the server was using 1.0. This has been fixed, though there are a lot of missing builds, I manually built the latest commit and pushed it to the server.

**Comment by astronautlevel2** [comment]
Closing this since updates don't require release.zip anymore
